# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41dcebea096023d0f3ac51ee23cddc238b472f9e8b32644bc56c208c200216ba20a79597fcfdf6f2cfdf61c8dd900db61e485549a8e94b7d2d687a5fae35a832

test:
  secret_key_base: 6b83ff235db5bf46293dc3d7eae953fb5dd225aa9da670958d68242f66fb254d157fc7125983cbbdda7453865507f0e6ded35dafcbaa608597525cd468be05d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
